#!/usr/bin/node
fs = require("fs")
child_process = require("child_process")

var files = {path:[],time:[]}
fs.readdirSync(__dirname+"/src").forEach((v,i,a)=>{
  files.path.push(__dirname+"/src/"+v)
  files.time.push(fs.statSync(__dirname+"/src/"+v).ctimeMs)
  
})
//console.log(files)
arrayMaxOf = (a)=>{
  
  var mi = 0,i=1
  for(;i<a.length;i++){
   //console.log(mi,a[mi])
    
    if(a[i] > a[mi]){
      mi = i
    }
  }
  return mi
}

last = files.path[arrayMaxOf(files.time)]

console.log("last is "+last)

if(/(.js)$/i.test(last)){
  console.log("lang is Javascript")
  //child_process.execSync("node "+last)
  //child_process.execFileSync("node",[last])
  //child_process.exec("node "+last,()=>{})
  cp = child_process.spawn("node",[last])
  
}

if(/(.c)$/i.test(last)){
  console.log("lang is C")
}

cp.stdout.pipe(process.stdout)
cp.stderr.pipe(process.stderr)

//process.stdin.pipe(cp.stdin)


/*
cp.stdout.on("data",(data)=>{
  //process.stdout.write(data)
  console.log(data.toString("utf-8"))
})

*/